---
- name: setup ntp
  hosts: servers
  become: true
  vars:
    ntp_manage_config: true
    ntp_servers:
      - "time.microsoft.com iburst"
  roles:
    - geerlingguy.ntp

- name: generate ssh keys for user lab
  hosts: localhost
  tasks:
    - name: key-gen
      shell:
        cmd: 'user=lab ; ssh-keygen -t ecdsa -b 521 -C "$user" -N "" -f ~/.ssh/$user 1> /dev/null ; cat ~/.ssh/$user.pub'
      register: key_lab

- name: generate ssh keys for user labsudo
  hosts: localhost
  tasks:
    - name: key-gen
      shell:
        cmd: 'user=labsudo ; ssh-keygen -t ecdsa -b 521 -C "$user" -N "" -f ~/.ssh/$user 1> /dev/null ; cat ~/.ssh/$user.pub'
      register: key_labsudo

- name: add user labsudo
  hosts: servers
  become: true
  vars:
    users:
      - name: labsudo
        username: labsudo
        groups: [sudo]
        shell: /bin/bash
        ssh_key: "{{ hostvars['localhost']['key_labsudo'].stdout_lines }}"
  roles:
    - singleplatform-eng.users

- name: add user lab
  hosts: servers
  become: true
  vars:
    users:
      - name: lab
        username: lab
        shell: /bin/bash
        ssh_key: "{{ hostvars['localhost']['key_lab'].stdout_lines }}"
  roles:
    - singleplatform-eng.users

- name: logrotate syslog
  hosts: servers
  become: true
  vars:
    logrotate_scripts:
      - name: syslog
        path: /var/log/syslog
        options:
          - daily
          - rotate 7
          - missingok
          - notifempty
        scripts:
          postrotate: "/usr/lib/rsyslog/rsyslog-rotate"
  roles:
    - nickhammond.logrotate

- name: install nginx
  hosts: frontend
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

- name: php-fpm
  hosts: backend
  become: true
  tasks:
    - name: ensure php-fpm is at the latest version
      apt: name=php-fpm state=latest
    - name: start php-fpm
      service:
          name: php7.3-fpm
          state: started

- name: install mysql
  hosts: database
  become: true
  tasks:
    - name: ensure mysql is at the latest version
      apt: name=mariadb-server state=latest
    - name: start mysql
      service:
          name: mysql
          state: started

- name: logrotate nginx
  hosts: frontend
  become: true
  vars:
    logrotate_scripts:
      - name: syslog
        path: /var/log/nginx/*.log
        options:
          - daily
          - rotate 7
          - missingok
          - notifempty
          - create 0640 www-data adm
          - sharedscripts
        scripts:
          postrotate: "invoke-rc.d nginx rotate >/dev/null 2>&1"
  roles:
    - nickhammond.logrotate

- name: logrotate php-fpm
  hosts: backend
  become: true
  vars:
    logrotate_scripts:
      - name: php-fpm
        path: /var/log/php-fpm.log
        options:
          - daily
          - rotate 7
          - missingok
          - notifempty
  roles:
    - nickhammond.logrotate

- name: logrotate mysql
  hosts: database
  become: true
  vars:
    logrotate_scripts:
      - name: mysql-server
        path: /var/log/mysql/*
        options:
          - daily
          - rotate 7
          - create 640 mysql adm
          - missingok
        scripts:
          postrotate: "/usr/bin/mysqladmin flush-logs"
  roles:
    - nickhammond.logrotate
